POST http://localhost:3001/add_question_to_quiz HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "quizId" : "64c04fd0ac8cac778efd4110",
    "questionText" : "What is the meaning of phrase 'How are you?'",
    "questionType" : "radio",
    "choices" : [{"choiceText" : "comment vas-tu ?"}, {"choiceText" : "qui es-tu"}, {"choiceText" : "toi"}],
    "correctChoiceText" : "comment vas-tu ?"
}

