POST http://localhost:3001/verify_token HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "token" : "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNhM2JkODk4ZGE1MGE4OWViOWUxY2YwYjdhN2VmZTM1OTNkNDEwNjgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGFza2Zsb3ctYm9hcmRzIiwiYXVkIjoidGFza2Zsb3ctYm9hcmRzIiwiYXV0aF90aW1lIjoxNzAyMzI1NTIzLCJ1c2VyX2lkIjoieDFOSVdwUEhXWVRIYjIwNWZqalJDNmJ1RWdMMiIsInN1YiI6IngxTklXcFBIV1lUSGIyMDVmampSQzZidUVnTDIiLCJpYXQiOjE3MDIzOTEwMTksImV4cCI6MTcwMjM5NDYxOSwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqb2huZG9lQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.UvUBTatlYRIQj8TWGE8eE24DllFT-G0XBDhDgEaiWpyDPsOCMffcKdTjz8U_zdvuBOKLilSyJUhjbykh00SKRZQr9GaiWrGGcHr9eHFzMY7oALmOhqzlUHmLL7AFNS_3zUw7rqY7SpaZ_uBgn34ooy_SxZ0MXxhuEQp8jyRuExuiMUTbRORRRUaaNirUgfZ8L08o4tE-sjVnBC8FRiiFgVwGuKwuh_fu3faadr1PvLT4KqTroWt1VumOp50OGALktBBNz0C_Hl1mVMBBVBkxRImSfcWa1F8lJj4tbopRpvMnzWkLSptbkzyr6m5R17SXmzpWiTtIHhulXpfCyo4CuQ"
}
