POST http://localhost:3001/create_quiz HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "quizName" : "Tech Quiz",
    "token" : "eyJhbGciOiJSUzI1NiIsImtpZCI6IjAzMmNjMWNiMjg5ZGQ0NjI2YTQzNWQ3Mjk4OWFlNDMyMTJkZWZlNzgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGFza2Zsb3ctYm9hcmRzIiwiYXVkIjoidGFza2Zsb3ctYm9hcmRzIiwiYXV0aF90aW1lIjoxNzAzMzM3ODE5LCJ1c2VyX2lkIjoieDFOSVdwUEhXWVRIYjIwNWZqalJDNmJ1RWdMMiIsInN1YiI6IngxTklXcFBIV1lUSGIyMDVmampSQzZidUVnTDIiLCJpYXQiOjE3MDMzNDQ0NTYsImV4cCI6MTcwMzM0ODA1NiwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqb2huZG9lQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.BGCl0UOC9NE1QKFCez3yE8g_fftVQCDS-gzW8iXCC0x2kwujkfmxRnzh17N-OK8gb11AFtJb1_kF2QH6ccDFpPXJGgWen3JEdyjluuNXlNZuUC0hlZg7BrBZyqtNQU-F9hmlQeszLIdyKRwVAGaKOTkpbYiUevMZcuiuK4bu6kr0kkgmQNVeaSP3lzTsLzZuhjMQO3qkqIiv3D7fn0JToMSIKsEcXUZC9RxNFdc6incSyRQFBVbUa8R_i8rffv-_7ihsWAYp3xnjNaLw0FbirYMRZ5w05SmXP5kVr1AGycPvT9RH2rHgnY7QXJwrLLxrnK5FFk2ejjGcf2iJI42ZIQ",
    "category" : "Entertainment",
    "isTimed" : false,
    "description" : "This is a basic tech quiz that assess general tech knowledge."
}