POST http://localhost:3001/onboard_user HTTP/1.1
Content-Type: application/json

{
    "token" : "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNhM2JkODk4ZGE1MGE4OWViOWUxY2YwYjdhN2VmZTM1OTNkNDEwNjgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGFza2Zsb3ctYm9hcmRzIiwiYXVkIjoidGFza2Zsb3ctYm9hcmRzIiwiYXV0aF90aW1lIjoxNzAyMjk4ODg4LCJ1c2VyX2lkIjoieDFOSVdwUEhXWVRIYjIwNWZqalJDNmJ1RWdMMiIsInN1YiI6IngxTklXcFBIV1lUSGIyMDVmampSQzZidUVnTDIiLCJpYXQiOjE3MDIyOTg4ODgsImV4cCI6MTcwMjMwMjQ4OCwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqb2huZG9lQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.RPNj4uP935Czz02GqbZrDpAW7YFKJpVz54N1Yr93-4whZe1Y46-cErsGnPe3xMitMpsVe2GItvmUP1INPmQM-Hlow0O1cOOC_08Oo_CRazWg8w3KL8sUyOdrO95dzlFMcEEUldwvuIp7tNo_yE_rlLtCgZMRS8GELBCQ4epcegS1xTye9-eDAKkSCR8r1EaB64XsCgc_IKasgyliRk8xTuCxjW1CNkTatcs5swdgjsKsAeA1dKgxCpcyu3mxuHA6q__9zbeJx6A3w6-Va3cMcVYZroIsk3veFCyfXO4gaMvXC1KxHINmPvgbwk0LpNPM0fW9JakRI6ILoPyb8Tv6wg",
    "name" : "Piyush"
}