POST http://localhost:3001/submit_quiz HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "token" : "eyJhbGciOiJSUzI1NiIsImtpZCI6IjY5NjI5NzU5NmJiNWQ4N2NjOTc2Y2E2YmY0Mzc3NGE3YWE5OTMxMjkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGFza2Zsb3ctYm9hcmRzIiwiYXVkIjoidGFza2Zsb3ctYm9hcmRzIiwiYXV0aF90aW1lIjoxNzA3MjQyMDgwLCJ1c2VyX2lkIjoieDFOSVdwUEhXWVRIYjIwNWZqalJDNmJ1RWdMMiIsInN1YiI6IngxTklXcFBIV1lUSGIyMDVmampSQzZidUVnTDIiLCJpYXQiOjE3MDcyNDIwODAsImV4cCI6MTcwNzI0NTY4MCwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqb2huZG9lQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.cFMVrQ0Lwox0U3C0_6zhG0_hxh9A_9pQdalNykd_S7pCZZYnxr6_wSDVE_D6AQFzSl3QiXqxU9gLr_MlXQbzKfKucfSgqqBvqvZ2sAiP0ocGOZ1cbkq5rutbKdDTrxKPqMxU5d-qvzJuPZVMu8JcOjhPpiMChJeRsBYG-zHcdIaXzgC5sff45gP9U3hh4lXvGL3kLZtl3aZp9ZlsojIKWurVda4WWFRIVmYNyOxUd2W9FsnJLlmJ2Gi12ttNiwdrl19QBucEyyNGQbLFdcRMLYW_pOQClt0drgVuDNs93uUP0CipB9W0Aw6Q4rF49sVB0N3nYN8s4ja0XwPQxbWZFA",
    "quizPayload" : {}
}

