POST http://localhost:3001/verify_token HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "token" : "eyJhbGciOiJSUzI1NiIsImtpZCI6ImJlNzgyM2VmMDFiZDRkMmI5NjI3NDE2NThkMjA4MDdlZmVlNmRlNWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGFza2Zsb3ctYm9hcmRzIiwiYXVkIjoidGFza2Zsb3ctYm9hcmRzIiwiYXV0aF90aW1lIjoxNzAyMzI1NTIzLCJ1c2VyX2lkIjoieDFOSVdwUEhXWVRIYjIwNWZqalJDNmJ1RWdMMiIsInN1YiI6IngxTklXcFBIV1lUSGIyMDVmampSQzZidUVnTDIiLCJpYXQiOjE3MDI0MzQ0NjksImV4cCI6MTcwMjQzODA2OSwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqb2huZG9lQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.dIGEFjzS0o1QB_A3ielbvxTpO5sJ-OKUcPrwfwyUrh-FSe7SkZFqtcYTJ98yasSNJ_IwnkndRgZMHK7dpTlxPiZG-TZsdn8285g7nXXw1v8d2S-Nltlj5kEI7sQ859sktwsRC1SPKYV6SGgjHHvcFPXcOcKAOuq1JmEHAm9Lm1ebsrs28O7eT17c430kT75hkbM2M_9qR1HnLs2v2aGv6ZedvZAHbdzSBSPteKNvl-m1qfEF3K5wd7R7wmgV4yP61atUyX7SWwcNjdQX08izUgigOEKc0fJUQaYAJrNFHKU9mRmYtM0SnP-lIWAPNOqwVnWkhX46Dite_HKVEcAGXA"
}
